### ISSUE TITLE
After Failing Tests, PatternNotFound Errors for previously working tests

### ISSUE THREAD

**Issue by KeKs0r** [hemerajs/hemera#114] opened 2017-07-10 09:23 UTC
## Description
I have written some functional tests that are passing (TestSet 1) . I now started to create more tests (in another file) that currently fail (TestSet 2). While having this intermediate situation I observed a rather confusing behaviour:
I run my TestSet 1 which passes fine. Now I run all tests, which fails due to TestSet2. Also Jest does not exit, which usually indicates that there are some connections / processes / async things still happening. I kill jest via sigterm. If I now run TestSet 1 alone again, which previously worked I am getting a PatternNotFound Exception. 

Also just restarting the NATS server does not solve the issue.

## Expected Result
That TestSet 1 always passes, independent of previously ran TestSet 2.

## Your Environment
- NATS: 0.9.6
- Hemera: 1.3.7
- NodeJs: 8.1.3
- Operating System and version: osx

**Comment by StarpTech** [comment] 2017-07-10 10:33
Please isolate your problem in a snippet or repo. I can't reproduce such scenario. Thank you.

**Comment by KeKs0r** [comment] 2017-07-10 15:11
I think its actually more a Jest issue than hemera. But it would still be interesting to see why the behaviour differs after having a "zombie" instance running. I will try to make a tiny repo to reproduce.

**Comment by StarpTech** [comment] 2017-07-13 21:29
I will close this until we get more informations.

**Closed by StarpTech** 2017-07-13 21:29 UTC
